spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  security:
    oauth2:
      resourceserver:
        jwt:
          # TODO: Keycloak Realm setting -> Endpoints: OpenID Endpoints Configuration 링크 -> jwks_uri 주소
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8180/realms/template-dev/protocol/openid-connect/certs}

logging:
  level:
    com.springapitemplate: debug # TODO: basePackages 수정

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    # TODO: 로컬환경 데이터베이스 설정
    url: jdbc:h2:tcp://localhost/~/template
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
  # TODO: 개발환경 데이터베이스 설정

  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
  # TODO: 운영환경 데이터베이스 설정

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    com.springapitemplate: info # TODO: basePackages 수정

decorator:
  datasource:
    p6spy:
      enable-logging: false

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
